from __future__ import annotations

"""Generated by tools/export_single_file.py. Do not edit this file directly."""

# --- module: ai_client ---

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast
from urllib import error, request


@dataclass(slots=True)
class ApiConfig:
    api_key: str
    base_url: str
    model: str
    temperature: float
    timeout_seconds: int


def load_api_config(repo_root: Path) -> ApiConfig:
    env_values = _load_dotenv(repo_root / ".env")

    def resolve(name: str, fallback: str | None = None) -> str | None:
        if name in os.environ:
            return os.environ[name]
        if name in env_values:
            return env_values[name]
        return fallback

    api_key = resolve("AI_API_KEY") or resolve("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("API mode requires AI_API_KEY or OPENAI_API_KEY in .env or the environment.")

    base_url = (resolve("AI_BASE_URL") or resolve("OPENAI_BASE_URL") or "https://api.openai.com/v1").rstrip("/")
    model = resolve("AI_MODEL") or resolve("OPENAI_MODEL") or "gpt-4.1-mini"
    temperature_text = resolve("AI_TEMPERATURE") or "0.2"
    timeout_text = resolve("AI_TIMEOUT_SECONDS") or "120"

    try:
        temperature = float(temperature_text)
    except ValueError as error_value:
        raise RuntimeError(f"Invalid AI_TEMPERATURE value: {temperature_text}") from error_value
    try:
        timeout_seconds = int(timeout_text)
    except ValueError as error_value:
        raise RuntimeError(f"Invalid AI_TIMEOUT_SECONDS value: {timeout_text}") from error_value

    return ApiConfig(
        api_key=api_key,
        base_url=base_url,
        model=model,
        temperature=temperature,
        timeout_seconds=timeout_seconds,
    )


def run_remote_analysis(
    config: ApiConfig,
    *,
    prompt_text: str,
    diff_markdown: str,
    diff_json_text: str,
    summary_text: str,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "model": config.model,
        "temperature": config.temperature,
        "messages": [
            {
                "role": "system",
                "content": prompt_text,
            },
            {
                "role": "user",
                "content": (
                    "请基于以下材料完成分析。\n\n"
                    "【客观摘要】\n"
                    f"{summary_text}\n\n"
                    "【Diff Markdown】\n"
                    f"{diff_markdown}\n\n"
                    "【Diff JSON】\n"
                    f"{diff_json_text}"
                ),
            },
        ],
        "response_format": {"type": "text"},
    }

    response_payload = _post_json(
        url=f"{config.base_url}/chat/completions",
        api_key=config.api_key,
        payload=payload,
        timeout_seconds=config.timeout_seconds,
    )
    choices = response_payload.get("choices")
    if not isinstance(choices, list) or not choices:
        raise RuntimeError("Remote AI response does not contain choices.")
    first_choice = cast(dict[str, Any], choices[0])
    message = cast(dict[str, Any] | None, first_choice.get("message"))
    if not isinstance(message, dict):
        raise RuntimeError("Remote AI response message is missing.")
    content = message.get("content")
    if not isinstance(content, str) or not content.strip():
        raise RuntimeError("Remote AI response content is empty.")
    return {
        "model": config.model,
        "base_url": config.base_url,
        "content": content.strip(),
        "raw_response": response_payload,
    }


def _load_dotenv(dotenv_path: Path) -> dict[str, str]:
    if not dotenv_path.exists():
        return {}
    values: dict[str, str] = {}
    for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        values[name.strip()] = value.strip().strip('"').strip("'")
    return values


def _post_json(url: str, api_key: str, payload: dict[str, Any], timeout_seconds: int) -> dict[str, Any]:
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    http_request = request.Request(
        url,
        data=data,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with request.urlopen(http_request, timeout=timeout_seconds) as response:
            body = response.read().decode("utf-8")
    except error.HTTPError as http_error:
        body = http_error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Remote AI request failed with HTTP {http_error.code}: {body}") from http_error
    except error.URLError as url_error:
        raise RuntimeError(f"Remote AI request failed: {url_error.reason}") from url_error

    try:
        decoded = json.loads(body)
    except json.JSONDecodeError as decode_error:
        raise RuntimeError("Remote AI response is not valid JSON.") from decode_error
    if not isinstance(decoded, dict):
        raise RuntimeError("Remote AI response root must be a JSON object.")
    return cast(dict[str, Any], decoded)

# --- module: models ---

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


@dataclass(slots=True)
class FileChange:
    file_path: str
    file_type: str
    before_ref: str | None
    after_ref: str | None
    status: str
    previous_path: str | None = None


@dataclass(slots=True)
class CommitEvent:
    commit_id: str
    author: str
    time: str
    message: str
    changed_files: list[FileChange]


@dataclass(slots=True)
class CommitComparison:
    before: CommitEvent
    after: CommitEvent
    changed_files: list[FileChange]
    description: str


@dataclass(slots=True)
class NormalizedRow:
    row_key: str
    values: dict[str, str]
    source_index: int


@dataclass(slots=True)
class NormalizedTable:
    source_path: str
    table_name: str
    headers: list[str]
    rows: list[NormalizedRow]
    key_field: str | None


@dataclass(slots=True)
class StructuredDiff:
    table: str
    row_key: str
    column: str
    before_value: str
    after_value: str
    change_type: str


@dataclass(slots=True)
class RiskItem:
    risk_type: str
    severity: str
    confidence: float
    evidence: str
    impact: str


@dataclass(slots=True)
class TodoItem:
    title: str
    priority: str
    owner_hint: str
    due_hint: str
    action: str
    verify_steps: str
    evidence: str


@dataclass(slots=True)
class FileAnalysis:
    commit_id: str
    file_change: FileChange
    diffs: list[StructuredDiff] = field(default_factory=list)
    key_changes: list[str] = field(default_factory=list)
    risks: list[RiskItem] = field(default_factory=list)
    todos: list[TodoItem] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass(slots=True)
class AnalysisReport:
    summary: str
    key_changes: list[str]
    risks: list[RiskItem]
    todos: list[TodoItem]
    metrics: dict[str, Any]
    commits: list[CommitEvent]
    files: list[FileAnalysis]
    warnings: list[str] = field(default_factory=list)
    output_dir: str = ""

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        if self.output_dir:
            data["output_dir"] = str(Path(self.output_dir))
        return data

# --- module: diffing ---



def _row_map(table: NormalizedTable) -> dict[str, dict[str, str]]:
    return {row.row_key: row.values for row in table.rows}


def diff_tables(before: list[NormalizedTable], after: list[NormalizedTable]) -> list[StructuredDiff]:
    before_map = {table.table_name: table for table in before}
    after_map = {table.table_name: table for table in after}
    diffs: list[StructuredDiff] = []
    for table_name in sorted(set(before_map) | set(after_map)):
        before_table = before_map.get(table_name)
        after_table = after_map.get(table_name)
        if before_table is None and after_table is not None:
            diffs.append(
                StructuredDiff(
                    table=table_name,
                    row_key="*",
                    column="*",
                    before_value="",
                    after_value="present",
                    change_type="table_added",
                )
            )
            continue
        if before_table is not None and after_table is None:
            diffs.append(
                StructuredDiff(
                    table=table_name,
                    row_key="*",
                    column="*",
                    before_value="present",
                    after_value="",
                    change_type="table_removed",
                )
            )
            continue
        assert before_table is not None and after_table is not None
        before_headers = set(before_table.headers)
        after_headers = set(after_table.headers)
        for column in sorted(after_headers - before_headers):
            diffs.append(
                StructuredDiff(
                    table=table_name,
                    row_key="*",
                    column=column,
                    before_value="",
                    after_value="present",
                    change_type="column_added",
                )
            )
        for column in sorted(before_headers - after_headers):
            diffs.append(
                StructuredDiff(
                    table=table_name,
                    row_key="*",
                    column=column,
                    before_value="present",
                    after_value="",
                    change_type="column_removed",
                )
            )
        before_rows = _row_map(before_table)
        after_rows = _row_map(after_table)
        all_headers = list(dict.fromkeys([*before_table.headers, *after_table.headers]))
        for row_key in sorted(set(before_rows) | set(after_rows)):
            before_row = before_rows.get(row_key)
            after_row = after_rows.get(row_key)
            if before_row is None and after_row is not None:
                diffs.append(
                    StructuredDiff(
                        table=table_name,
                        row_key=row_key,
                        column="*",
                        before_value="",
                        after_value="present",
                        change_type="row_added",
                    )
                )
                continue
            if before_row is not None and after_row is None:
                diffs.append(
                    StructuredDiff(
                        table=table_name,
                        row_key=row_key,
                        column="*",
                        before_value="present",
                        after_value="",
                        change_type="row_deleted",
                    )
                )
                continue
            assert before_row is not None and after_row is not None
            for header in all_headers:
                before_value = before_row.get(header, "")
                after_value = after_row.get(header, "")
                if before_value != after_value:
                    diffs.append(
                        StructuredDiff(
                            table=table_name,
                            row_key=row_key,
                            column=header,
                            before_value=before_value,
                            after_value=after_value,
                            change_type="cell_changed",
                        )
                    )
    return diffs

# --- module: git_ops ---

import subprocess
from dataclasses import dataclass
from pathlib import Path



TEXT_EXTENSIONS = {
    ".csv": "csv",
    ".json": "json",
    ".txt": "text",
    ".md": "text",
    ".yaml": "text",
    ".yml": "text",
}
EXCEL_EXTENSIONS = {
    ".xlsx": "excel",
    ".xlsm": "excel",
    ".xltx": "excel",
    ".xltm": "excel",
    ".xls": "excel-legacy",
    ".xlsb": "excel-binary",
}


@dataclass(slots=True)
class GitRefs:
    commit_ids: list[str]
    description: str


def _run_git(repo: Path, args: list[str], *, check: bool = True, binary: bool = False) -> str | bytes:
    completed = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=False,
        capture_output=True,
    )
    if check and completed.returncode != 0:
        stderr = completed.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(f"git {' '.join(args)} failed: {stderr}")
    return completed.stdout if binary else completed.stdout.decode("utf-8", errors="replace")


def detect_file_type(file_path: str) -> str:
    suffix = Path(file_path).suffix.lower()
    if suffix in EXCEL_EXTENSIONS:
        return EXCEL_EXTENSIONS[suffix]
    if suffix in TEXT_EXTENSIONS:
        return TEXT_EXTENSIONS[suffix]
    return "other"


def _repo_relative_path(repo: Path, path: Path) -> str:
    repo_root = repo.resolve()
    candidate = path if path.is_absolute() else repo_root / path
    candidate = candidate.resolve()
    try:
        return candidate.relative_to(repo_root).as_posix()
    except ValueError as error:
        raise RuntimeError(f"Path filter '{path}' must be inside repository '{repo_root}'.") from error


def resolve_commit_ids(
    repo: Path,
    *,
    since: str | None,
    until: str | None,
    base: str | None,
    head: str,
) -> GitRefs:
    if base:
        commit_text = _run_git(repo, ["rev-list", "--reverse", f"{base}..{head}"])
        description = f"{base}..{head}"
    elif since or until:
        args = ["rev-list", "--reverse"]
        if since:
            args.append(f"--since={since}")
        if until:
            args.append(f"--until={until}")
        args.append(head)
        commit_text = _run_git(repo, args)
        description = f"time range since={since or '-'} until={until or '-'} head={head}"
    else:
        commit_text = _run_git(repo, ["rev-list", "--max-count=1", head])
        description = f"latest commit at {head}"
    commit_ids = [line.strip() for line in commit_text.splitlines() if line.strip()]
    if not commit_ids:
        raise RuntimeError("No commits found for the requested range.")
    return GitRefs(commit_ids=commit_ids, description=description)


def _select_comparison_commits(repo: Path, commit_ids: list[str]) -> tuple[str | None, str]:
    if len(commit_ids) >= 2:
        return commit_ids[0], commit_ids[-1]
    target_commit = commit_ids[-1]
    return _commit_parent(repo, target_commit), target_commit


def _commit_parent(repo: Path, commit_id: str) -> str | None:
    line = _run_git(repo, ["rev-list", "--parents", "-n", "1", commit_id]).strip()
    parts = line.split()
    if len(parts) > 1:
        return parts[1]
    return None


def _commit_metadata(repo: Path, commit_id: str) -> tuple[str, str, str]:
    raw = _run_git(repo, ["show", "-s", "--format=%an%n%aI%n%s", commit_id])
    author, time, message = raw.splitlines()[:3]
    return author, time, message


def _parse_name_status_line(line: str) -> tuple[str, str | None, str]:
    parts = line.split("\t")
    status = parts[0]
    if status.startswith("R") or status.startswith("C"):
        return status, parts[1], parts[2]
    return status, None, parts[1]


def _collect_file_changes(
    repo: Path,
    before_commit: str | None,
    after_commit: str,
    pathspecs: list[str] | None = None,
) -> list[FileChange]:
    if before_commit:
        args = ["diff", "--find-renames", "--name-status", before_commit, after_commit]
        if pathspecs:
            args.extend(["--", *pathspecs])
        raw_changes = _run_git(repo, args)
    else:
        args = ["diff-tree", "--root", "--no-commit-id", "--name-status", "-r", after_commit]
        if pathspecs:
            args.extend(["--", *pathspecs])
        raw_changes = _run_git(repo, args)

    changed_files: list[FileChange] = []
    for line in raw_changes.splitlines():
        if not line.strip():
            continue
        status, previous_path, file_path = _parse_name_status_line(line)
        source_path = file_path
        before_path = previous_path or source_path
        file_type = detect_file_type(source_path)
        before_ref = f"{before_commit}:{before_path}" if before_commit and not status.startswith("A") else None
        after_ref = f"{after_commit}:{source_path}" if not status.startswith("D") else None
        changed_files.append(
            FileChange(
                file_path=source_path,
                file_type=file_type,
                before_ref=before_ref,
                after_ref=after_ref,
                status=status,
                previous_path=previous_path,
            )
        )
    return changed_files


def collect_commit_comparison(
    repo: Path,
    *,
    since: str | None,
    until: str | None,
    base: str | None,
    head: str,
    target_path: Path | None = None,
) -> CommitComparison:
    refs = resolve_commit_ids(repo, since=since, until=until, base=base, head=head)
    before_commit, after_commit = _select_comparison_commits(repo, refs.commit_ids)
    assert after_commit is not None

    before_author = before_time = before_message = ""
    if before_commit:
        before_author, before_time, before_message = _commit_metadata(repo, before_commit)
    after_author, after_time, after_message = _commit_metadata(repo, after_commit)

    pathspecs = [_repo_relative_path(repo, target_path)] if target_path is not None else None
    changed_files = _collect_file_changes(repo, before_commit, after_commit, pathspecs)
    before_event = CommitEvent(
        commit_id=before_commit or "<empty>",
        author=before_author,
        time=before_time,
        message=before_message,
        changed_files=[],
    )
    after_event = CommitEvent(
        commit_id=after_commit,
        author=after_author,
        time=after_time,
        message=after_message,
        changed_files=changed_files,
    )
    return CommitComparison(
        before=before_event,
        after=after_event,
        changed_files=changed_files,
        description=f"{before_event.commit_id if before_commit else 'root'}..{after_event.commit_id}",
    )


def read_blob(repo: Path, ref: str | None) -> bytes | None:
    if ref is None:
        return None
    try:
        return _run_git(repo, ["show", ref], binary=True)  # type: ignore[return-value]
    except RuntimeError:
        return None

# --- module: normalize ---

import csv
import io
import json
from pathlib import Path
from zipfile import BadZipFile


KEY_CANDIDATES = ("id", "key", "code", "name")


def _stringify(value: object) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _sanitize_headers(raw_headers: list[object], width: int) -> list[str]:
    headers: list[str] = []
    seen: dict[str, int] = {}
    for index in range(width):
        base = _stringify(raw_headers[index]) if index < len(raw_headers) else ""
        base = base or f"column_{index + 1}"
        seen[base] = seen.get(base, 0) + 1
        header = base if seen[base] == 1 else f"{base}_{seen[base]}"
        headers.append(header)
    return headers


def _select_key_field(headers: list[str]) -> str | None:
    lowered = {header.lower(): header for header in headers}
    for candidate in KEY_CANDIDATES:
        for lowered_header, header in lowered.items():
            if lowered_header == candidate or lowered_header.endswith(f"_{candidate}") or lowered_header.startswith(f"{candidate}_"):
                return header
    return headers[0] if headers else None


def _row_key(values: dict[str, str], key_field: str | None, row_index: int) -> str:
    if key_field:
        candidate = values.get(key_field, "").strip()
        if candidate:
            return candidate
    return f"row:{row_index}"


def _build_table(source_path: str, table_name: str, raw_rows: list[list[object]]) -> NormalizedTable:
    width = max((len(row) for row in raw_rows), default=0)
    if width == 0:
        return NormalizedTable(source_path=source_path, table_name=table_name, headers=[], rows=[], key_field=None)
    headers = _sanitize_headers(raw_rows[0], width)
    key_field = _select_key_field(headers)
    rows: list[NormalizedRow] = []
    for source_index, raw_row in enumerate(raw_rows[1:], start=2):
        padded_row = [_stringify(raw_row[index]) if index < len(raw_row) else "" for index in range(width)]
        if not any(padded_row):
            continue
        values = dict(zip(headers, padded_row))
        rows.append(
            NormalizedRow(
                row_key=_row_key(values, key_field, source_index),
                values=values,
                source_index=source_index,
            )
        )
    return NormalizedTable(
        source_path=source_path,
        table_name=table_name,
        headers=headers,
        rows=rows,
        key_field=key_field,
    )


def parse_csv_tables(source_path: str, content: bytes) -> list[NormalizedTable]:
    text = content.decode("utf-8-sig", errors="replace")
    reader = csv.reader(io.StringIO(text))
    rows = [list(row) for row in reader]
    return [_build_table(source_path, Path(source_path).name, rows)]


def parse_json_tables(source_path: str, content: bytes) -> list[NormalizedTable]:
    payload = json.loads(content.decode("utf-8-sig", errors="replace"))
    if isinstance(payload, list) and payload and all(isinstance(item, dict) for item in payload):
        keys: list[str] = []
        for item in payload:
            for key in item.keys():
                if key not in keys:
                    keys.append(str(key))
        rows: list[list[object]] = [keys]
        rows.extend([[item.get(key) for key in keys] for item in payload])  # type: ignore[union-attr]
        return [_build_table(source_path, Path(source_path).name, rows)]
    if isinstance(payload, dict):
        rows = [["field", "value"], *[[key, json.dumps(value, ensure_ascii=False, sort_keys=True)] for key, value in payload.items()]]
        return [_build_table(source_path, Path(source_path).name, rows)]
    rows = [["value"], [json.dumps(payload, ensure_ascii=False, sort_keys=True)]]
    return [_build_table(source_path, Path(source_path).name, rows)]


def parse_excel_tables(source_path: str, content: bytes) -> list[NormalizedTable]:
    try:
        from openpyxl import load_workbook
        from openpyxl.utils.exceptions import InvalidFileException
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "Excel analysis requires openpyxl. Install it with 'python -m pip install .[excel]' "
            "or 'python -m pip install openpyxl'."
        ) from error
    try:
        workbook = load_workbook(io.BytesIO(content), data_only=False, read_only=True)
    except (BadZipFile, InvalidFileException, ValueError) as error:
        raise RuntimeError(f"failed to parse Excel content ({error})") from error
    tables: list[NormalizedTable] = []
    for worksheet in workbook.worksheets:
        raw_rows = [list(row) for row in worksheet.iter_rows(values_only=True)]
        tables.append(_build_table(source_path, worksheet.title, raw_rows))
    return tables


def parse_text_tables(source_path: str, content: bytes) -> list[NormalizedTable]:
    text = content.decode("utf-8-sig", errors="replace")
    rows = [["line_number", "content"]]
    rows.extend([[index, line] for index, line in enumerate(text.splitlines(), start=1)])
    return [_build_table(source_path, Path(source_path).name, rows)]


def load_tables(source_path: str, file_type: str, content: bytes) -> tuple[list[NormalizedTable], list[str]]:
    warnings: list[str] = []
    if not content:
        return [], warnings
    if file_type == "csv":
        return parse_csv_tables(source_path, content), warnings
    if file_type == "json":
        try:
            return parse_json_tables(source_path, content), warnings
        except json.JSONDecodeError as error:
            warnings.append(f"{source_path}: invalid JSON content ({error}).")
            return [], warnings
    if file_type == "text":
        return parse_text_tables(source_path, content), warnings
    if file_type == "excel":
        try:
            return parse_excel_tables(source_path, content), warnings
        except RuntimeError as error:
            warnings.append(f"{source_path}: {error}")
            return [], warnings
    if file_type == "excel-legacy":
        warnings.append(f"{source_path}: .xls is not supported in MVP; please convert it to .xlsx for structured diff.")
        return [], warnings
    if file_type == "excel-binary":
        warnings.append(f"{source_path}: .xlsb is not supported in MVP; please convert it to .xlsx for structured diff.")
        return [], warnings
    warnings.append(f"{source_path}: unsupported file type for structured diff.")
    return [], warnings


def write_normalized_tables(tables: list[NormalizedTable], output_dir: Path, label: str) -> list[str]:
    artifact_paths: list[str] = []
    output_dir.mkdir(parents=True, exist_ok=True)
    for table in tables:
        safe_name = "".join(character if character.isalnum() or character in {"-", "_"} else "_" for character in table.table_name)
        target_path = output_dir / f"{label}__{safe_name}.csv"
        with target_path.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(table.headers)
            for row in table.rows:
                writer.writerow([row.values.get(header, "") for header in table.headers])
        artifact_paths.append(str(target_path))
    return artifact_paths

# --- module: reporting ---

from dataclasses import asdict
import json
from pathlib import Path
from typing import Any, cast



def _markdown_escape(value: str) -> str:
    return value.replace("\n", "<br>").replace("|", "\\|")


def build_diff_context(report: AnalysisReport, range_description: str) -> dict[str, object]:
    commits = report.commits[:2]
    before_commit = commits[0] if len(commits) > 0 else None
    after_commit = commits[1] if len(commits) > 1 else None

    def commit_summary(commit: object | None) -> dict[str, object] | None:
        if commit is None:
            return None
        return {
            "commit_id": getattr(commit, "commit_id", None),
            "author": getattr(commit, "author", None),
            "time": getattr(commit, "time", None),
            "message": getattr(commit, "message", None),
        }

    return {
        "range_description": range_description,
        "comparison": {
            "before": commit_summary(before_commit),
            "after": commit_summary(after_commit),
        },
        "metrics": report.metrics,
        "warnings": report.warnings,
        "files": [
            {
                "commit_id": file_report.commit_id,
                "file_path": file_report.file_change.file_path,
                "previous_path": file_report.file_change.previous_path,
                "file_type": file_report.file_change.file_type,
                "status": file_report.file_change.status,
                "before_ref": file_report.file_change.before_ref,
                "after_ref": file_report.file_change.after_ref,
                "warnings": file_report.warnings,
                "diffs": [asdict(diff) for diff in file_report.diffs],
            }
            for file_report in report.files
            if file_report.file_change.file_type != "other"
        ],
    }


def build_diff_markdown(report: AnalysisReport, range_description: str) -> str:
    context = build_diff_context(report, range_description)
    comparison = cast(dict[str, object], context["comparison"])
    before_commit = cast(dict[str, object] | None, comparison.get("before"))
    after_commit = cast(dict[str, object] | None, comparison.get("after"))
    before_line = "-"
    after_line = "-"
    if isinstance(before_commit, dict):
        before_line = f"{before_commit.get('commit_id', '-')}: {before_commit.get('message', '-') or '-'}"
    if isinstance(after_commit, dict):
        after_line = f"{after_commit.get('commit_id', '-')}: {after_commit.get('message', '-') or '-'}"

    sections: list[str] = [
        "# 客观 Diff 上下文",
        "",
        "## 比较范围",
        "",
        f"- 范围：{range_description}",
        f"- 变更前提交：{before_line}",
        f"- 变更后提交：{after_line}",
        "",
        "## 统计",
        "",
        f"- commit_count: {report.metrics.get('commit_count', 0)}",
        f"- changed_file_count: {report.metrics.get('changed_file_count', 0)}",
        f"- analyzed_file_count: {report.metrics.get('analyzed_file_count', 0)}",
        f"- diff_count: {report.metrics.get('diff_count', 0)}",
        f"- risk_count: {report.metrics.get('risk_count', 0)}",
        f"- todo_count: {report.metrics.get('todo_count', 0)}",
        "",
        "## 文件级差异",
        "",
    ]

    files = cast(list[dict[str, object]], context["files"])
    if files:
        for file_entry in files:
            sections.extend(
                [
                    f"### {file_entry.get('file_path', '-')}",
                    "",
                    f"- 类型：{file_entry.get('file_type', '-')}",
                    f"- 状态：{file_entry.get('status', '-')}",
                    f"- 旧路径：{file_entry.get('previous_path') or '-'}",
                    f"- before_ref：{file_entry.get('before_ref') or '-'}",
                    f"- after_ref：{file_entry.get('after_ref') or '-'}",
                ]
            )
            warnings = cast(list[object], file_entry.get("warnings") or [])
            if warnings:
                sections.append("- 警告：")
                sections.extend(f"  - {str(warning)}" for warning in warnings)
            diffs = cast(list[dict[str, object]], file_entry.get("diffs") or [])
            if diffs:
                sections.extend([
                    "",
                    "| table | row_key | column | change_type | before_value | after_value |",
                    "| --- | --- | --- | --- | --- | --- |",
                ])
                for diff in diffs:
                    sections.append(
                        "| {table} | {row_key} | {column} | {change_type} | {before_value} | {after_value} |".format(
                            table=_markdown_escape(str(diff.get("table", "-"))),
                            row_key=_markdown_escape(str(diff.get("row_key", "-"))),
                            column=_markdown_escape(str(diff.get("column", "-"))),
                            change_type=_markdown_escape(str(diff.get("change_type", "-"))),
                            before_value=_markdown_escape(str(diff.get("before_value", ""))),
                            after_value=_markdown_escape(str(diff.get("after_value", ""))),
                        )
                    )
            else:
                sections.append("- 无结构化差异。")
            sections.append("")
    else:
        sections.append("- 无可分析的结构化文件变更。")

    if report.warnings:
        sections.extend(["## 全局警告", ""])
        sections.extend(f"- {warning}" for warning in report.warnings)
        sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def build_prompt_text(range_description: str) -> str:
    _ = range_description
    return "# CommitChangeAnalyzer AI Prompt\n\n你是一个提交变更分析助手。你的任务是基于输入的客观 diff 上下文，输出语义化、可执行的分析结论。\n\n## 输入\n\n你会收到以下材料：\n\n1. `diff-context.md`：人类可读的结构化差异上下文。\n2. `diff-context.json`：与上面一致的结构化 JSON。\n3. 必要时还会附上 `analysis-report.md` / `analysis-report.json` 作为补充。\n\n## 目标\n\n请把“事实”转成“意义”。重点回答：何种条目对应的哪些内容从 A 变成了 B。\n\n## 输出要求\n\n请严格按下面的结构输出，尽量简洁但不要失真：\n\n1. `summary`\n\n- 用 1 到 3 句话概括本次变化的核心结论。\n- 优先使用“从 A 变为 B”“新增了”“删除了”“清空了”这类表达。\n\n2. `key_changes`\n\n- 列出最重要的语义变化。\n- 每条都要尽量写成“对象 + 字段 + 变化前 + 变化后 + 影响方向”。\n\n3. `risks`\n\n- 只写可从 diff 直接推导出的风险，不要凭空扩展。\n- 每条风险都要附上对应证据或文件路径。\n\n4. `todos`\n\n- 一句话给出可执行的后续动作。\n\n5. `questions`\n\n- 如果有关键上下文缺失，列出需要人工确认的问题。\n- 没有问题就输出空列表。\n\n## 写作风格\n\n- 以事实为基础，不要使用空泛的“已修改”“发生变化”“进行了调整”之类表述。\n- 需要时直接说“<对象> 的 <字段> 从 A 变为 B”。\n- 不要把规则分析结果当成最终语义结论，必要时要主动解释其业务影响。\n- 不要编造未出现在 diff 里的背景知识。\n\n## 质量标准\n\n一条好的结论应该满足：\n\n- 能指出具体对象。\n- 能指出变化前后。\n- 能说明为什么这件事重要。\n- 能落到后续动作或验证方式。\n\n## 示例句式\n\n- “表 `RewardConfig` 中 `DropRate` 从 `0.1` 变为 `0.2`，会直接影响掉落概率。”\n- “行 `Item_1001` 从存在变为不存在，需要确认是否仍被活动脚本引用。”\n- “字段 `RoleId` 从 `A001` 变为 `A009`，会影响关联主键和跨表引用。”\n\n## 输出格式建议\n\n如果你需要结构化输出，建议使用 JSON 或分节 Markdown，并确保每条结论都能回溯到 diff 证据。\n"

def write_report(
    report: AnalysisReport,
    output_dir: Path,
    range_description: str,
    mode: str,
    ai_result: dict[str, Any] | None = None,
) -> dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    markdown_path = output_dir / "analysis-report.md"
    json_path = output_dir / "analysis-report.json"
    todo_path = output_dir / "todo-list.json"
    diff_markdown_path = output_dir / "diff-context.md"
    diff_json_path = output_dir / "diff-context.json"
    prompt_path = output_dir / "ai-prompt.md"

    ai_artifact_line = ""
    ai_section = ""
    if ai_result is not None:
        ai_model = str(ai_result.get("model", "-"))
        ai_content = str(ai_result.get("content", "")).strip()
        ai_artifact_line = "\nAI 最终产物：ai-analysis.md、ai-analysis.json"
        ai_section = f"""

## AI 分析结果

模型：`{ai_model}`

{ai_content or 'AI 已执行，但未返回可展示内容。'}
"""

    markdown = f"""# 提交变更分析报告

{report.summary}

分析范围：`{range_description}`
运行模式：`{mode}`
指标：commits={report.metrics.get('commit_count', 0)}, changed_files={report.metrics.get('changed_file_count', 0)}, analyzed_files={report.metrics.get('analyzed_file_count', 0)}, diffs={report.metrics.get('diff_count', 0)}

AI 中间产物：{diff_markdown_path.name}、{diff_json_path.name}、{prompt_path.name}{ai_artifact_line}{ai_section}
"""
    markdown_path.write_text(markdown, encoding="utf-8")
    json_payload = report.to_dict()
    if ai_result is not None:
        json_payload["ai_analysis"] = ai_result
    json_path.write_text(json.dumps(json_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    todo_path.write_text(
        json.dumps([asdict(todo) for todo in report.todos], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    diff_markdown_path.write_text(build_diff_markdown(report, range_description), encoding="utf-8")
    diff_json_path.write_text(json.dumps(build_diff_context(report, range_description), ensure_ascii=False, indent=2), encoding="utf-8")
    prompt_path.write_text(build_prompt_text(range_description), encoding="utf-8")
    return {
        "markdown": str(markdown_path),
        "json": str(json_path),
        "todo_json": str(todo_path),
        "diff_markdown": str(diff_markdown_path),
        "diff_json": str(diff_json_path),
        "prompt": str(prompt_path),
    }

# --- module: rules ---

from collections import defaultdict


ID_HINTS = ("id", "key", "code")
BALANCE_HINTS = ("hp", "attack", "damage", "drop", "reward", "rate", "ratio", "cost", "price", "exp", "score")


def _contains_hint(name: str, hints: tuple[str, ...]) -> bool:
    lowered = name.lower()
    return any(hint in lowered for hint in hints)


def _is_number(value: str) -> bool:
    if not value:
        return False
    try:
        float(value)
        return True
    except ValueError:
        return False


def _priority_for_severity(severity: str) -> str:
    return {
        "critical": "P0",
        "high": "P1",
        "medium": "P1",
        "low": "P2",
    }[severity]


def _transition(before_value: str, after_value: str) -> str:
    before_text = before_value or "空"
    after_text = after_value or "空"
    return f"从 {before_text} 变为 {after_text}"


def analyze_diffs(file_path: str, diffs: list[StructuredDiff], warnings: list[str]) -> tuple[list[str], list[RiskItem], list[TodoItem]]:
    key_changes: list[str] = []
    buckets: dict[str, dict[str, object]] = defaultdict(lambda: {"severity": "low", "count": 0, "evidence": []})

    def add_bucket(bucket: str, severity: str, evidence: str) -> None:
        current = buckets[bucket]
        current["count"] = int(current["count"]) + 1
        if severity_order(severity) > severity_order(str(current["severity"])):
            current["severity"] = severity
        evidence_list = current["evidence"]
        if isinstance(evidence_list, list) and len(evidence_list) < 3:
            evidence_list.append(evidence)

    for diff in diffs:
        evidence = f"{file_path}::{diff.table} row={diff.row_key} column={diff.column} type={diff.change_type}"
        if diff.change_type in {"table_added", "table_removed"}:
            add_bucket("schema-change", "high", evidence)
            if diff.change_type == "table_added":
                key_changes.append(f"{file_path} 的表 {diff.table} 从不存在变为存在。")
            else:
                key_changes.append(f"{file_path} 的表 {diff.table} 从存在变为不存在。")
            continue
        if diff.change_type in {"column_added", "column_removed"}:
            add_bucket("schema-change", "high", evidence)
            if diff.change_type == "column_added":
                key_changes.append(f"{file_path} 的表 {diff.table} 字段 {diff.column} 从不存在变为存在。")
            else:
                key_changes.append(f"{file_path} 的表 {diff.table} 字段 {diff.column} 从存在变为不存在。")
            continue
        if diff.change_type == "row_deleted":
            add_bucket("row-deletion", "high", evidence)
            key_changes.append(f"{file_path} 的表 {diff.table} 中的行 {diff.row_key} 从存在变为不存在。")
            continue
        if diff.change_type == "row_added":
            add_bucket("row-addition", "low", evidence)
            key_changes.append(f"{file_path} 的表 {diff.table} 中新增了行 {diff.row_key}。")
            continue
        if _contains_hint(diff.column, ID_HINTS):
            add_bucket("identifier-change", "critical", evidence)
            key_changes.append(
                f"{file_path} 的表 {diff.table} 行 {diff.row_key} 的标识字段 {diff.column} {_transition(diff.before_value, diff.after_value)}。"
            )
            continue
        if diff.before_value and not diff.after_value:
            add_bucket("value-cleared", "medium", evidence)
            key_changes.append(
                f"{file_path} 的表 {diff.table} 行 {diff.row_key} 的字段 {diff.column} 从 {diff.before_value} 变为空。"
            )
            continue
        if _contains_hint(diff.column, BALANCE_HINTS) and _is_number(diff.before_value) and _is_number(diff.after_value):
            add_bucket("balance-change", "high", evidence)
            key_changes.append(
                f"{file_path} 的表 {diff.table} 行 {diff.row_key} 的数值字段 {diff.column} {_transition(diff.before_value, diff.after_value)}。"
            )
            continue
        if _is_number(diff.before_value) and _is_number(diff.after_value):
            add_bucket("numeric-change", "medium", evidence)
            key_changes.append(
                f"{file_path} 的表 {diff.table} 行 {diff.row_key} 的字段 {diff.column} {_transition(diff.before_value, diff.after_value)}。"
            )

    for warning in warnings:
        add_bucket("unsupported-file", "medium", warning)
        key_changes.append(warning)

    risk_templates = {
        "schema-change": ("结构变更", "可能影响字段兼容性、下游读取逻辑或跨表引用关系。"),
        "row-deletion": ("数据删除", "可能导致引用失效、配置缺失或线上行为变化。"),
        "row-addition": ("新增数据", "需要确认新增配置是否已完成联调和验证。"),
        "identifier-change": ("标识字段变更", "主键或唯一标识变化可能导致引用链断裂。"),
        "value-cleared": ("关键值被清空", "清空字段可能触发默认值、空引用或配置异常。"),
        "balance-change": ("数值平衡变更", "数值调整可能影响战斗、掉落或奖励平衡。"),
        "numeric-change": ("数值字段变化", "数值变动需要业务确认是否符合预期。"),
        "unsupported-file": ("文件暂不可结构化分析", "该文件需要人工转换后再进行精确 diff。"),
    }

    todo_templates = {
        "schema-change": ("确认字段与下游兼容性", "数据负责人", "本次迭代内", "检查所有依赖该表的读取逻辑和脚本，确认字段新增/删除是否需要同步更新。", "在相关系统完成回归并确认读取成功。"),
        "row-deletion": ("核对删除数据的引用影响", "模块负责人", "提交前", "确认被删除数据是否仍被脚本、关卡或配置引用，必要时补迁移说明。", "搜索引用点并完成一次相关场景验证。"),
        "row-addition": ("确认新增数据接入链路", "策划/程序协作", "提测前", "检查新增配置是否已被代码、脚本或资源正确消费。", "验证新增配置在目标场景中生效。"),
        "identifier-change": ("核对主键或标识字段修改", "模块负责人", "立即", "确认所有引用该标识的表、脚本和逻辑是否同步更新。", "完成引用搜索并通过一次关键路径回归。"),
        "value-cleared": ("确认被清空字段是否允许为空", "数据负责人", "提测前", "核实清空字段是否有默认值保护，必要时补配置说明。", "确认运行时不会因空值报错或走错逻辑。"),
        "balance-change": ("复核关键数值调整", "策划负责人", "提测前", "复核数值改动意图，并安排相关玩法/掉落回归。", "通过目标场景的数值回归验证。"),
        "numeric-change": ("确认一般数值变更", "数据负责人", "提测前", "确认数值变更来源和预期影响，必要时补充说明。", "抽样核对变更后的行为与预期一致。"),
        "unsupported-file": ("转换不支持的 Excel 文件", "工具维护人", "下次分析前", "将不支持的文件格式转换为 .xlsx 并重新执行分析。", "重新生成结构化 diff 并确认无遗漏。"),
    }

    risks: list[RiskItem] = []
    todos: list[TodoItem] = []
    for bucket_name, bucket in sorted(buckets.items()):
        title, impact = risk_templates[bucket_name]
        evidence_lines = bucket["evidence"]
        evidence_text = "\n".join(f"- {line}" for line in evidence_lines) if isinstance(evidence_lines, list) else str(evidence_lines)
        severity = str(bucket["severity"])
        risks.append(
            RiskItem(
                risk_type=title,
                severity=severity,
                confidence=min(0.99, 0.55 + int(bucket["count"]) * 0.1),
                evidence=evidence_text,
                impact=impact,
            )
        )
        todo_title, owner_hint, due_hint, action, verify_steps = todo_templates[bucket_name]
        todos.append(
            TodoItem(
                title=todo_title,
                priority=_priority_for_severity(severity),
                owner_hint=owner_hint,
                due_hint=due_hint,
                action=action,
                verify_steps=verify_steps,
                evidence=evidence_text,
            )
        )
    return key_changes, risks, todos


def severity_order(severity: str) -> int:
    return {
        "low": 1,
        "medium": 2,
        "high": 3,
        "critical": 4,
    }[severity]

# --- module: orchestrator ---

from dataclasses import dataclass
import json
from pathlib import Path



@dataclass(slots=True)
class AnalyzerConfig:
    repo: Path
    output_dir: Path
    since: str | None
    until: str | None
    base: str | None
    head: str
    target_path: Path | None
    mode: str


def run_analysis(config: AnalyzerConfig) -> dict[str, str]:
    comparison = collect_commit_comparison(
        config.repo,
        since=config.since,
        until=config.until,
        base=config.base,
        head=config.head,
        target_path=config.target_path,
    )

    file_reports: list[FileAnalysis] = []
    warnings: list[str] = []
    key_changes: list[str] = []
    risks = []
    todos = []
    changed_file_count = len(comparison.changed_files)

    if config.mode not in {"rule", "api"}:
        warnings.append(f"Mode '{config.mode}' is not implemented yet; falling back to rule-only analysis.")

    artifact_root = config.output_dir / "artifacts"
    for file_change in comparison.changed_files:
        analysis = FileAnalysis(commit_id=comparison.after.commit_id, file_change=file_change)
        if file_change.file_type == "other":
            analysis.warnings.append(f"{file_change.file_path}: skipped unsupported file type.")
            file_reports.append(analysis)
            warnings.extend(analysis.warnings)
            continue

        before_blob = read_blob(config.repo, file_change.before_ref)
        after_blob = read_blob(config.repo, file_change.after_ref)
        before_tables, before_warnings = load_tables(file_change.previous_path or file_change.file_path, file_change.file_type, before_blob or b"")
        after_tables, after_warnings = load_tables(file_change.file_path, file_change.file_type, after_blob or b"")
        analysis.warnings.extend(before_warnings)
        analysis.warnings.extend(after_warnings)

        if file_change.file_type == "excel":
            artifact_dir = artifact_root / comparison.description / Path(file_change.file_path).stem
            write_normalized_tables(before_tables, artifact_dir, "before")
            write_normalized_tables(after_tables, artifact_dir, "after")

        analysis.diffs = diff_tables(before_tables, after_tables)
        analysis.key_changes, analysis.risks, analysis.todos = analyze_diffs(
            file_change.file_path,
            analysis.diffs,
            analysis.warnings,
        )
        file_reports.append(analysis)
        warnings.extend(analysis.warnings)
        key_changes.extend(analysis.key_changes)
        risks.extend(analysis.risks)
        todos.extend(analysis.todos)

    analyzed_files = [item for item in file_reports if item.file_change.file_type != "other"]
    summary = f"Compared {comparison.description} across {len(analyzed_files)} supported file change(s)."
    report = AnalysisReport(
        summary=summary,
        key_changes=dedupe(key_changes),
        risks=risks,
        todos=todos,
        metrics={
            "commit_count": 2,
            "changed_file_count": changed_file_count,
            "analyzed_file_count": len(analyzed_files),
            "diff_count": sum(len(item.diffs) for item in file_reports),
            "risk_count": len(risks),
            "todo_count": len(todos),
        },
        commits=[comparison.before, comparison.after],
        files=file_reports,
        warnings=dedupe(warnings),
        output_dir=str(config.output_dir),
    )
    range_description = comparison.description
    if config.target_path is not None:
        range_description = f"{comparison.description} / path={config.target_path.as_posix()}"
    outputs = write_report(report, config.output_dir, range_description, config.mode)

    if config.mode == "api":
        try:
            api_config = load_api_config(config.repo)
            prompt_text = build_prompt_text(range_description)
            diff_markdown = build_diff_markdown(report, range_description)
            diff_json_text = json.dumps(build_diff_context(report, range_description), ensure_ascii=False, indent=2)
            remote_result = run_remote_analysis(
                api_config,
                prompt_text=prompt_text,
                diff_markdown=diff_markdown,
                diff_json_text=diff_json_text,
                summary_text=report.summary,
            )
            ai_markdown_path = config.output_dir / "ai-analysis.md"
            ai_json_path = config.output_dir / "ai-analysis.json"
            ai_markdown_path.write_text(str(remote_result["content"]), encoding="utf-8")
            ai_json_path.write_text(json.dumps(remote_result, ensure_ascii=False, indent=2), encoding="utf-8")
            outputs = write_report(report, config.output_dir, range_description, config.mode, ai_result=remote_result)
            outputs["ai_markdown"] = str(ai_markdown_path)
            outputs["ai_json"] = str(ai_json_path)
        except RuntimeError as error:
            warning_text = f"API analysis skipped: {error}"
            warnings.append(warning_text)
            report.warnings = dedupe(warnings)
            outputs = write_report(report, config.output_dir, range_description, config.mode)

    return outputs


def dedupe(values: list[str]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            ordered.append(value)
    return ordered

# --- module: cli ---

import argparse
from pathlib import Path



def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="commit-change-analyzer",
        description="Analyze commit changes and generate a markdown report plus a todo list.",
    )
    parser.add_argument("--repo", default=".", help="Repository path to analyze.")
    parser.add_argument("--output-dir", default="output", help="Directory for generated reports.")
    parser.add_argument("--since", help="Git --since expression, such as '2026-05-01'.")
    parser.add_argument("--until", help="Git --until expression, such as '2026-05-16'.")
    parser.add_argument("--base", help="Base commit or branch for range analysis.")
    parser.add_argument("--head", default="HEAD", help="Head commit or branch for range analysis.")
    parser.add_argument(
        "--path",
        dest="target_path",
        help="Repository subdirectory or file path to include in the analysis.",
    )
    parser.add_argument(
        "--mode",
        choices=["rule", "agent", "api"],
        default="rule",
        help="Analysis mode: rule for local-only output, api for remote AI analysis after local diff generation.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    config = AnalyzerConfig(
        repo=Path(args.repo).resolve(),
        output_dir=Path(args.output_dir).resolve(),
        since=args.since,
        until=args.until,
        base=args.base,
        head=args.head,
        target_path=Path(args.target_path) if args.target_path else None,
        mode=args.mode,
    )
    outputs = run_analysis(config)
    print("Analysis completed.")
    for name, path in outputs.items():
        print(f"{name}: {path}")
    return 0

def _generated_entrypoint() -> int:
    return main()


if __name__ == "__main__":
    raise SystemExit(_generated_entrypoint())
